schemaVersion = "1.0"
id = "lcod://contract/core/http/request@1.0.0"
name = "request"
namespace = "contract/core/http"
version = "1.0.0"
kind = "contract"
summary = "Perform an HTTP request with configurable method, headers, body, and streaming hints."

[tool]
name = "core_http_request"
description = "Low-level HTTP client supporting query params, headers, and response metadata."
inputSchema = "schema/request.in.json"
outputSchema = "schema/request.out.json"

[hints]
timeoutMs = 10000

[docs]
readme = "README.md"
