schemaVersion = "2.0"
id = "lcod://tooling/value/is_object@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Check whether a value is a non-null object."

[palette]
category = "Validation"
icon = "mdi:code-json"
tags = [ "validation" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.value]
summary = "Value to inspect."
required = false
schema = "{}"

[outputs.ok]
summary = "True when the value is an object excluding arrays."
schema = """
{
  "type": "boolean"
}"""

[documentation]
body = "Check whether a value is a non-null object."
