schemaVersion = "1.0"
id = "lcod://tooling/value/is_object@0.1.0"
name = "is_object"
namespace = "tooling/value"
version = "0.1.0"
kind = "component"

summary = "Check whether a value is a non-null object."

[palette]
category = "Validation"
icon = "mdi:code-json"
tags = ["validation"]

[docs]
readme = "README.md"

[[io.input]]
name = "value"
type = "any"
required = false
description = "Value to inspect."

[[io.output]]
name = "ok"
type = "boolean"
description = "True when the value is an object excluding arrays."

[deps]
requires = [
  "lcod://tooling/script@1"
]
