schemaVersion = "1.0"
id = "lcod://contract/core/parse/toml@1.0.0"
name = "toml"
namespace = "contract/core/parse"
version = "1.0.0"
kind = "contract"
summary = "Parse TOML text into a JSON-compatible object."

[tool]
name = "core_parse_toml"
description = "Parses TOML strings (from text/file/stream) and returns structured data."
inputSchema = "schema/toml.in.json"
outputSchema = "schema/toml.out.json"

[hints]
timeoutMs = 2000

[docs]
readme = "README.md"
