schemaVersion = "1.0"
id = "lcod://contract/core/parse/csv@1.0.0"
name = "csv"
namespace = "contract/core/parse"
version = "1.0.0"
kind = "contract"
summary = "Parse CSV data into JSON rows, exposing the result as a stream handle or array depending on size."

[tool]
name = "core_parse_csv"
description = "Streams CSV rows as JSON objects (optionally with headers) for use in foreach pipelines."
inputSchema = "schema/csv.in.json"
outputSchema = "schema/csv.out.json"

[hints]
timeoutMs = 10000

[docs]
readme = "README.md"
