schemaVersion = "2.0"
id = "lcod://contract/tooling/fs/write_if_changed@1.0.0"
version = "1.0.0"
kind = "contract"
summary = "Write text to a file only when the contents change."

[tool]
name = "tooling_fs_write_if_changed"
description = "Persists a string to disk if it differs from the current file." 
inputSchema = "schema/write_if_changed.in.json"
outputSchema = "schema/write_if_changed.out.json"

[documentation]
body = """
Normalises the provided content to a string, compares it with the current file
contents (using the requested encoding) and writes the file only when the data
changes. The contract reports whether the file was modified.
"""
