compose:
- call: lcod://flow/foreach@1
  in:
    list: $.numbers
  children:
    body:
    - call: lcod://impl/is_even@1
      in:
        value: $slot.item
      out:
        isEven: ok
    - call: lcod://flow/if@1
      in:
        cond: $.isEven
      children:
        then:
        - call: lcod://flow/continue@1
    - call: lcod://impl/gt@1
      in:
        value: $slot.item
        limit: 7
      out:
        tooBig: ok
    - call: lcod://flow/if@1
      in:
        cond: $.tooBig
      children:
        then:
        - call: lcod://flow/break@1
    - call: lcod://impl/echo@1
      in:
        value: $slot.item
      out:
        val: val
  collectPath: $.val
  out:
    results: results
