schemaVersion = "2.0"
id = "lcod://flow/foreach_ctrl_demo@0.1.0"
version = "0.1.0"
kind = "function"
summary = "Foreach demo with continue/break and collectPath."

[deps]
requires = [
  "lcod://flow/foreach@1",
  "lcod://flow/continue@1",
  "lcod://flow/break@1",
  "lcod://flow/if@1",
  "lcod://impl/echo@1",
  "lcod://impl/is_even@1",
  "lcod://impl/gt@1"
]

[tool]
name = "foreach_ctrl_demo"
description = "Skip even numbers, break > 7, collect echoed values."
inputSchema = "schema/foreach_ctrl_demo.in.json"
outputSchema = "schema/foreach_ctrl_demo.out.json"

[documentation]
body = """
Demonstrates `continue` and `break` in `lcod://flow/foreach@1`:
- Skip even numbers via `is_even` + `flow/continue@1`
- Stop at the first number greater than 7 via `gt` + `flow/break@1`
- Collects the echoed values via `collectPath: "$.val"`

Input: `{ "numbers": [1,2,3,8,9] }`
Output: `{ "results": [1,3] }`"""
