schemaVersion = "2.0"
id = "lcod://tooling/array/flatten@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Flatten an array one level deep, discarding nullish entries."

[palette]
category = "Array"
icon = "mdi:arrange-bring-forward"
tags = [ "array" ]

[deps]
requires = [ "lcod://contract/tooling/array/flatten@1" ]

[inputs.items]
summary = "Array to flatten."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.values]
summary = "Flattened array without nullish entries."
schema = """
{
  "type": "array"
}"""

[documentation]
body = """
Returns a new array composed of the non-null values from the input sequence.
Nested arrays are expanded by one level, while `null` and `undefined` entries
are removed."""
