schemaVersion = "1.0"
id = "lcod://tooling/registry/catalog/generate@0.1.0"
name = "registry_catalog_generate"
namespace = "tooling/registry"
version = "0.1.0"
kind = "function"
summary = "Generate registry.json and packages.jsonl content from a catalog definition."

[tool]
name = "Registry Catalog Generator"
description = "Builds registry indexes (JSON/JSONL) from catalog and versions metadata."
outputSchema = "schema/generate.out.json"

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://axiom/path/join@1",
  "lcod://axiom/fs/read-file@1"
]
