schemaVersion = "1.0"
id = "lcod://tooling/path/is_absolute@0.1.0"
name = "is_absolute"
namespace = "tooling/path"
version = "0.1.0"
kind = "component"

summary = "Check whether a path is absolute."

[palette]
category = "Filesystem"
icon = "mdi:sign-direction"
tags = ["path", "absolute"]

[docs]
readme = "README.md"

[[io.input]]
name = "path"
type = "string"
required = false
description = "Path to analyse."

[[io.output]]
name = "absolute"
type = "boolean"
description = "True when the provided path is absolute."

[deps]
requires = [
  "lcod://tooling/script@1"
]
