schemaVersion = "2.0"
id = "lcod://tooling/path/is_absolute@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Check whether a path is absolute."

[palette]
category = "Filesystem"
icon = "mdi:sign-direction"
tags = [ "path", "absolute" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.path]
summary = "Path to analyse."
required = false
schema = """
{
  "type": "string"
}"""

[outputs.absolute]
summary = "True when the provided path is absolute."
schema = """
{
  "type": "boolean"
}"""

[documentation]
body = """
Detect whether a path is absolute. Supports Unix-style absolute paths and
Windows drive-prefixed paths."""
