schemaVersion = "1.0"
id = "lcod://contract/core/fs/list-dir@1.0.0"
name = "list-dir"
namespace = "contract/core/fs"
version = "1.0.0"
kind = "contract"
summary = "List directory entries with optional metadata."

[tool]
name = "fs_list_dir"
description = "Enumerate directory contents, optionally including stats and filtering options."
inputSchema = "schema/list_dir.in.json"
outputSchema = "schema/list_dir.out.json"

[hints]
timeoutMs = 5000

[docs]
readme = "README.md"
