compose:
  - call: lcod://tooling/script@1
    in:
      source: |
        async ({ state }) => {
          const input = typeof state.path === 'string' ? state.path : '';
          if (!input.length) return { dirname: '.' };

          const stripTrailing = (value) => {
            let result = value;
            while (result.length > 1 && (result.endsWith('/') || result.endsWith('\\'))) {
              result = result.slice(0, -1);
            }
            return result;
          };

          const trimmed = stripTrailing(input);
          const lastSlash = Math.max(trimmed.lastIndexOf('/'), trimmed.lastIndexOf('\\'));
          if (lastSlash === -1) return { dirname: '.' };
          if (lastSlash === 0) {
            return { dirname: trimmed[0] === '/' || trimmed[0] === '\\' ? trimmed[0] : '.' };
          }
          const dirname = trimmed.slice(0, lastSlash);
          return { dirname: dirname.length ? dirname : '.' };
        }
      input:
        path: $.path
    out:
      dirname: dirname
