compose:
  - call: lcod://tooling/value/is_object@0.1.0
    in:
      value: $.value
    out:
      isObject: ok
  - call: lcod://flow/if@1
    in:
      cond: $.isObject
    out:
      resolved: resolved
    slots:
      then:
        - call: lcod://impl/set@1
          in:
            resolved: $.value
          out:
            resolved: resolved
      else:
        - call: lcod://tooling/value/is_object@0.1.0
          in:
            value: $.fallback
          out:
            fallbackIsObject: ok
        - call: lcod://flow/if@1
          in:
            cond: $.fallbackIsObject
          out:
            resolved: resolved
          slots:
            then:
              - call: lcod://impl/set@1
                in:
                  resolved: $.fallback
                out:
                  resolved: resolved
            else:
              - call: lcod://impl/set@1
                in:
                  resolved: {}
                out:
                  resolved: resolved
