schemaVersion = "1.0"
id = "lcod://tooling/value/default_object@0.1.0"
name = "default_object"
namespace = "tooling/value"
version = "0.1.0"
kind = "component"

summary = "Return the value when it is an object, otherwise fallback to a default."

[palette]
category = "Utility"
icon = "mdi:code-braces-box"
tags = ["value", "object"]

[docs]
readme = "README.md"

[[io.input]]
name = "value"
type = "any"
required = false
description = "Candidate value to normalize."

[[io.input]]
name = "fallback"
type = "object"
required = false
description = "Fallback object returned when the candidate is not an object."

[[io.output]]
name = "value"
type = "object"
description = "Normalized object."

[deps]
requires = [
  "lcod://tooling/value/is_object@0.1.0",
  "lcod://flow/if@1",
  "lcod://impl/set@1"
]
