compose:
  - call: lcod://tooling/value/is_array@0.1.0
    in:
      value: $.value
    out:
      isArray: ok

  - call: lcod://flow/if@1
    in:
      cond: $.isArray
    children:
      then:
        - call: lcod://impl/set@1
          in:
            resolved: $.value
          out:
            resolved: resolved
      else:
        - call: lcod://tooling/value/is_array@0.1.0
          in:
            value: $.fallback
          out:
            fallbackIsArray: ok
        - call: lcod://flow/if@1
          in:
            cond: $.fallbackIsArray
          children:
            then:
              - call: lcod://impl/set@1
                in:
                  resolved: $.fallback
                out:
                  resolved: resolved
            else:
              - call: lcod://impl/set@1
                in:
                  resolved: []
                out:
                  resolved: resolved
          out:
            resolved: resolved
    out:
      resolved: resolved
