schemaVersion = "2.0"
id = "lcod://tooling/value/default_array@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Return the value when it is an array, otherwise fallback to a default array."

[palette]
category = "Utility"
icon = "mdi:format-list-bulleted"
tags = [ "value", "array" ]

[deps]
requires = [
  "lcod://tooling/value/is_array@0.1.0",
  "lcod://flow/if@1",
  "lcod://impl/set@1"
]

[inputs.value]
summary = "Candidate list to normalize."
required = false
schema = "{}"

[inputs.fallback]
summary = "Fallback array returned when the candidate is not an array."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.value]
summary = "Normalized array."
schema = """
{
  "type": "array"
}"""

[documentation]
body = """
Return the provided value when it is an array; otherwise fall back to the
supplied default (or an empty array)."""
