schemaVersion = "1.0"
id = "lcod://contract/core/object/merge@1.0.0"
name = "merge"
namespace = "contract/core/object"
version = "1.0.0"
kind = "contract"
summary = "Merge two objects into a new structure without mutating the inputs."

[tool]
name = "core_object_merge"
description = "Merge two objects (shallow by default, optional deep merge)."
inputSchema = "schema/merge.in.json"
outputSchema = "schema/merge.out.json"

[docs]
readme = "README.md"
