compose:
  - call: lcod://tooling/value/default_object@0.1.0
    in:
      value: $.sourcesConfig
    out:
      sourcesConfig: resolved
  - call: lcod://impl/set@1
    in:
      defaultsCandidate: $.sourcesConfig.defaults
      sourcesCandidate: $.sourcesConfig.sources
      basePriority: $.sourcesConfig.defaults.priority
    out:
      defaultsCandidate: defaultsCandidate
      sourcesCandidate: sourcesCandidate
      basePriority: basePriority
  - call: lcod://tooling/value/default_object@0.1.0
    in:
      value: $.defaultsCandidate
    out:
      defaults: resolved
  - call: lcod://impl/set@1
    in:
      defaultEntrypointCandidate: $.defaults.entrypoint
      basePriority: $.defaults.priority
    out:
      defaultEntrypointCandidate: defaultEntrypointCandidate
      basePriority: basePriority
  - call: lcod://tooling/value/default_object@0.1.0
    in:
      value: $.defaultEntrypointCandidate
    out:
      defaultEntrypoint: resolved
  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.sourcesCandidate
    out:
      sourcesList: resolved
  - call: lcod://flow/foreach@1
    in:
      list: $.sourcesList
    collectPath: $.normalized
    out:
      rootNormalized: results
    slots:
      body:
        - call: lcod://tooling/registry_sources/normalize_pointer@0.1.0
          in:
            entry: $slot.item
            baseDir: $.sourcesBaseDir
            sourcesBaseDir: $.sourcesBaseDir
            defaultEntrypoint: $.defaultEntrypoint
            basePriority: $.basePriority
          out:
            pointer: pointer
            warnings: warnings
        - call: lcod://impl/set@1
          in:
            normalized:
              pointer: $.pointer
              warnings: $.warnings
          out:
            normalized: normalized
  - call: lcod://tooling/registry_sources/partition_normalized@0.1.0
    in:
      entries: $.rootNormalized
    out:
      rootPointers: pointers
      rootWarnings: warnings
  - call: lcod://tooling/registry_sources/collect_queue@0.1.0
    in:
      queue: $.rootPointers
      downloadsRoot: $.downloadsRoot
      sourcesBaseDir: $.sourcesBaseDir
      defaultEntrypoint: $.defaultEntrypoint
      basePriority: $.basePriority
    out:
      contributions: contributions
      queueWarnings: warnings
  - call: lcod://tooling/registry_sources/merge_inline_entries@0.1.0
    in:
      entries: $.contributions
    out:
      registrySources: registrySources
  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.rootWarnings
    out:
      rootWarnings: resolved
  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.queueWarnings
    out:
      queueWarnings: resolved
  - call: lcod://tooling/array/append@0.1.0
    in:
      items: $.rootWarnings
      values: $.queueWarnings
    out:
      warnings: items
  - call: lcod://impl/set@1
    in:
      registrySources: $.registrySources
      warnings: $.warnings
    out:
      registrySources: registrySources
      warnings: warnings
