schemaVersion = "2.0"
id = "lcod://tooling/registry_sources/collect_entries@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Fetch registry catalogues from the sources configuration and emit inline registry source entries."

[palette]
category = "Registry"
icon = "mdi:cloud-download"
tags = [ "registry", "catalogue", "sources" ]

[deps]
requires = [
  "lcod://flow/if@1",
  "lcod://flow/foreach@1",
  "lcod://tooling/array/append@0.1.0",
  "lcod://tooling/value/default_array@0.1.0",
  "lcod://tooling/value/default_object@0.1.0",
  "lcod://tooling/registry_sources/collect_queue@0.1.0",
  "lcod://tooling/registry_sources/merge_inline_entries@0.1.0",
  "lcod://tooling/registry_sources/normalize_pointer@0.1.0",
  "lcod://impl/set@1"
]

[inputs.sourcesConfig]
summary = "Parsed sources specification."
required = true
schema = """
{
  "type": "object"
}"""

[inputs.sourcesBaseDir]
summary = "Base directory used to resolve relative catalogue paths."
required = true
schema = """
{
  "type": "string"
}"""

[inputs.downloadsRoot]
summary = "Directory dedicated to downloaded catalogues."
required = true
schema = """
{
  "type": "string"
}"""

[outputs.registrySources]
summary = "Inline registry source entries derived from the catalogues."
schema = """
{
  "type": "array"
}"""

[outputs.warnings]
summary = "Warnings emitted while fetching and parsing catalogues."
schema = """
{
  "type": "array"
}"""

[documentation]
body = """
Materialise the inline registry sources defined by a `sources.json`
configuration. The component iterates over catalogue pointers, downloads or
reads their payloads (HTTP, Git or local files), validates the schema, and
emits inline source entries that can be consumed directly by the resolver."""
