schemaVersion = "2.0"
id = "lcod://ui/hello_button@0.1.0"
version = "0.1.0"
kind = "ui"
summary = "Minimal UI example with props."

[ui]
kind = "react"
propsSchema = "schema/props.json"
slots = [ "default" ]

[tool]
name = "hello_button"
description = "A button that emits a click event."
inputSchema = "schema/props.json"
outputSchema = "schema/events.json"

[documentation]
body = "Minimal UI component example with props and a simple event shape."
