schemaVersion = "1.0"
id = "lcod://ui/hello_button@0.1.0"
name = "hello_button"
namespace = "ui"
version = "0.1.0"
kind = "ui"
summary = "Minimal UI example with props."

[tool]
name = "hello_button"
description = "A button that emits a click event."
inputSchema = "schema/props.json"
outputSchema = "schema/events.json"

[ui]
kind = "react"
propsSchema = "schema/props.json"
slots = ["default"]

[docs]
readme = "README.md"

