schemaVersion = "1.0"
id = "lcod://tooling/registry_sources/build_inline_entry@0.1.0"
name = "build_inline_entry"
namespace = "tooling/registry_sources"
version = "0.1.0"
kind = "component"

summary = "Convert a processed catalogue entry into an inline registry source contribution."

[[io.input]]
name = "entry"
type = "object"
description = "Processed entry produced by `process_pointer`."

[[io.input]]
name = "pointer"
type = "object"
description = "Original normalized pointer (used for fallback metadata)."

[[io.output]]
name = "contribution"
type = "object"
description = "Inline contribution or null when the entry has no materialised lines."

[deps]
requires = ["lcod://tooling/script@1"]
