schemaVersion = "2.0"
id = "lcod://tooling/registry_sources/build_inline_entry@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Convert a processed catalogue entry into an inline registry source contribution."

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.entry]
summary = "Processed entry produced by `process_pointer`."
required = false
schema = """
{
  "type": "object"
}"""

[inputs.pointer]
summary = "Original normalized pointer (used for fallback metadata)."
required = false
schema = """
{
  "type": "object"
}"""

[outputs.contribution]
summary = "Inline contribution or null when the entry has no materialised lines."
schema = """
{
  "type": "object"
}"""
