schemaVersion = "2.0"
id = "lcod://tooling/path/join_chain@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Join path segments sequentially starting from an optional base."

[palette]
category = "Filesystem"
icon = "mdi:folder"
tags = [ "path", "filesystem" ]

[deps]
requires = [ "lcod://contract/tooling/path/join_chain@1" ]

[inputs.base]
summary = "Initial path segment."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.segments]
summary = "Segments to append in order."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.path]
summary = "Resolved path after applying all segments."
schema = """
{
  "type": "string"
}"""

[documentation]
body = """
Combines an initial path with additional segments using the host platform's
filesystem semantics. Nullish or empty segments are ignored."""
