schemaVersion = "2.0"
id = "lcod://tooling/path/join_chain@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Join a base path with a sequence of segments using path axioms."

[palette]
category = "Filesystem"
icon = "mdi:vector-polyline"
tags = [ "path", "join" ]

[deps]
requires = [ "lcod://tooling/script@1", "lcod://axiom/path/join@1" ]

[inputs.base]
summary = "Base path (defaults to empty string)."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.segments]
summary = "Ordered list of segments to append. Nullish entries are ignored."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.path]
summary = "Resulting joined path."
schema = """
{
  "type": "string"
}"""

[documentation]
body = """
Join a base path with an ordered list of segments. Null or empty segments are
skipped, and intermediate joins delegate to the standard `path/join` axiom."""
