schemaVersion = "1.0"
id = "lcod://tooling/compose/normalize@0.1.0"
name = "compose_normalize"
namespace = "tooling/compose"
version = "0.1.0"
kind = "function"
summary = "Normalize sugar syntax in compose definitions before execution."

[tool]
name = "Normalize Compose"
description = "Expands shorthand mappings (foo: -) and recursively normalizes children."
inputSchema = "schema/normalize.in.json"
outputSchema = "schema/normalize.out.json"

[deps]
requires = [
  "lcod://tooling/script@1"
]

[docs]
readme = "README.md"
