schemaVersion = "2.0"
id = "lcod://tooling/mcp/register_local@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Register MCP authoring components located on disk (e.g. lcod-components workspace) so they can be used in local workflows."

[palette]
category = "Authoring"
icon = "mdi:integration-helper"
tags = [ "mcp", "register", "workspace" ]

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://tooling/resolver/register@1",
  "lcod://axiom/path/join@1",
  "lcod://axiom/fs/read-file@1"
]

[inputs.componentsRoot]
summary = "Filesystem path containing MCP component directories (e.g. lcod-components/packages/std/components)."
required = true
schema = """
{
  "type": "string"
}"""

[outputs.registered]
summary = "Number of components successfully registered."
schema = """
{
  "type": "number"
}"""

[outputs.warnings]
summary = "Diagnostics collected while resolving or registering components."
schema = """
{
  "type": "array"
}"""
