schemaVersion = "2.0"
id = "lcod://tooling/registry/resolution@0.1.0"
version = "0.1.0"
kind = "function"
summary = "Load registry sources, index packages, and select entries for dependencies."

[deps]
requires = [
  "lcod://flow/if@1",
  "lcod://flow/foreach@1",
  "lcod://tooling/registry/source/load@0.1.0",
  "lcod://tooling/registry/select@0.1.0",
  "lcod://tooling/registry/index@0.1.0"
]

[tool]
name = "Registry Resolution"
description = "Combines registry/source/load, registry/index, and registry/select to produce a map of resolved versions for resolver."
inputSchema = "schema/resolution.in.json"
outputSchema = "schema/resolution.out.json"

[documentation]
body = """
Wraps the registry helpers into a single call:

1. Load sources via `tooling/registry/source/load@0.1.0`.
2. Index JSONL streams with `tooling/registry/index@0.1.0`.
3. For each requested component (id + optional range), select the best entry using
   `tooling/registry/select@0.1.0`.

Outputs the registry metadata plus the chosen entries, ready to be consumed by the
resolver compose."""
