schemaVersion = "2.0"
id = "lcod://tooling/registry_sources/merge_inline_entries@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Merge inline registry source contributions by id."

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.entries]
summary = "Inline contributions emitted while traversing catalogue pointers."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.registrySources]
summary = "Merged inline sources ready for the resolver."
schema = """
{
  "type": "array"
}"""
