schemaVersion = "2.0"
id = "lcod://tooling/value/is_defined@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Check whether a value is defined (not null or undefined)."

[palette]
category = "Validation"
icon = "mdi:check-bold"
tags = [ "validation" ]

[deps]
requires = [ "lcod://contract/tooling/value/is_defined@1" ]

[inputs.value]
summary = "Value to inspect."
required = false
schema = "{}"

[outputs.ok]
summary = "True when the value is defined."
schema = """
{
  "type": "boolean"
}"""

[documentation]
body = """
Returns whether the provided value is defined (i.e. neither `null` nor
`undefined`)."""
