schemaVersion = "2.0"
id = "lcod://contract/core/string/format@1.0.0"
version = "1.0.0"
kind = "contract"
summary = "Format a template string using named placeholders."

[tool]
name = "core_string_format"
description = "Perform named placeholder substitution on a template string."
inputSchema = "schema/format.in.json"
outputSchema = "schema/format.out.json"

[documentation]
body = """
Formats a template string using named placeholders. Placeholders follow the
`{placeholder}` syntax. Nested values can be referenced with dot notation (for
example `{user.name}`) and array indices (`{items[0]}`)."""
