schemaVersion = "1.0"
id = "lcod://contract/core/string/format@1.0.0"
name = "format"
namespace = "contract/core/string"
version = "1.0.0"
kind = "contract"
summary = "Format a template string using named placeholders."

[tool]
name = "core_string_format"
description = "Perform named placeholder substitution on a template string."
inputSchema = "schema/format.in.json"
outputSchema = "schema/format.out.json"

[docs]
readme = "README.md"
