schemaVersion = "2.0"
id = "lcod://tooling/json/decode_object@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Decode JSON text and ensure the result is an object, falling back when needed."

[palette]
category = "JSON"
icon = "mdi:code-json"
tags = [ "json", "decode" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.text]
summary = "JSON text to decode."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.fallback]
summary = "Fallback object returned when decoding fails or the value is not an object."
required = false
schema = """
{
  "type": "object"
}"""

[inputs.warningMessage]
summary = "Warning emitted when decoding fails (defaults to a generic message)."
required = false
schema = """
{
  "type": "string"
}"""

[outputs.value]
summary = "Decoded JSON object or fallback."
schema = """
{
  "type": "object"
}"""

[outputs.warnings]
summary = "Warning messages (empty when decoding succeeds)."
schema = """
{
  "type": "array"
}"""

[outputs.error]
summary = "Structured error when decoding fails or the result is not an object."
schema = """
{
  "type": "object"
}"""

[documentation]
body = """
Decode a JSON string and ensure the result is an object. When parsing fails or
produces a non-object value, a fallback object is returned along with a warning."""
