schemaVersion = "1.0"
id = "lcod://tooling/json/decode_object@0.1.0"
name = "decode_object"
namespace = "tooling/json"
version = "0.1.0"
kind = "component"

summary = "Decode JSON text and ensure the result is an object, falling back when needed."

[palette]
category = "JSON"
icon = "mdi:code-json"
tags = ["json", "decode"]

[docs]
readme = "README.md"

[[io.input]]
name = "text"
type = "string"
required = false
description = "JSON text to decode."

[[io.input]]
name = "fallback"
type = "object"
required = false
description = "Fallback object returned when decoding fails or the value is not an object."

[[io.input]]
name = "warningMessage"
type = "string"
required = false
description = "Warning emitted when decoding fails (defaults to a generic message)."

[[io.output]]
name = "value"
type = "object"
description = "Decoded JSON object or fallback."

[[io.output]]
name = "warnings"
type = "array"
description = "Warning messages (empty when decoding succeeds)."

[[io.output]]
name = "error"
type = "object"
description = "Structured error when decoding fails or the result is not an object."

[deps]
requires = [
  "lcod://tooling/script@1"
]
