schemaVersion = "1.0"
id = "lcod://project/http_app@0.1.0"
name = "http_app"
namespace = "project"
version = "0.1.0"
kind = "contract"
summary = "HTTP project contract that exposes sequences and API routes to a host."

[tool]
name = "http_app"
description = "Register HTTP routes and execution sequences for a project."
inputSchema = "schema/http_app.in.json"
outputSchema = "schema/http_app.out.json"

[docs]
readme = "README.md"
