schemaVersion = "2.0"
id = "lcod://tooling/registry_sources/partition_normalized@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Split normalized pointer tuples into a pointer list and accumulated warnings."

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.entries]
summary = "Tuples generated while normalizing catalogue pointers."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.pointers]
summary = "Valid normalized pointers ready to be enqueued."
schema = """
{
  "type": "array"
}"""

[outputs.warnings]
summary = "Flattened warnings emitted during normalization."
schema = """
{
  "type": "array"
}"""
