schemaVersion = "1.0"
id = "lcod://env/http_host@0.1.0"
name = "http_host"
namespace = "env"
version = "0.1.0"
kind = "contract"
summary = "HTTP environment contract that launches an HTTP server and registers child projects."

[tool]
name = "http_host"
description = "Start an HTTP host with routes produced by child projects."
inputSchema = "schema/http_host.in.json"
outputSchema = "schema/http_host.out.json"

[docs]
readme = "README.md"
