schemaVersion = "2.0"
id = "lcod://env/http_host@0.1.0"
version = "0.1.0"
kind = "contract"
summary = "HTTP environment contract that launches an HTTP server and registers child projects."

[tool]
name = "http_host"
description = "Start an HTTP host with routes produced by child projects."
inputSchema = "schema/http_host.in.json"
outputSchema = "schema/http_host.out.json"

[documentation]
body = """
Defines the contract for an HTTP hosting environment. The component receives the
basic network configuration (host, port, optional base path) and exposes a slot
`projects` that lets compose authors attach one or more HTTP projects.

Each project is expected to resolve to `lcod://project/http_app@0.1.0` (or a
compatible contract). The host implementation is responsible for invoking the
`projects` slot, collecting the routes returned by each project, and registering
them on the HTTP server."""
