schemaVersion = "2.0"
id = "lcod://tooling/path/to_file_url@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Convert an absolute filesystem path into a file:// URL."

[palette]
category = "Filesystem"
icon = "mdi:link-variant"
tags = [ "path", "url" ]

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.path]
summary = "Absolute filesystem path."
required = false
schema = """
{
  "type": "string"
}"""

[outputs.url]
summary = "Normalised file:// URL or null when the input is empty."
schema = """
{
  "type": "string"
}"""

[documentation]
body = """
Convert an absolute filesystem path into a normalised `file://` URL. Backslashes
are replaced by forward slashes and redundant `./` segments are removed."""
