schemaVersion = "1.0"
id = "lcod://tooling/path/to_file_url@0.1.0"
name = "to_file_url"
namespace = "tooling/path"
version = "0.1.0"
kind = "component"

summary = "Convert an absolute filesystem path into a file:// URL."

[palette]
category = "Filesystem"
icon = "mdi:link-variant"
tags = ["path", "url"]

[docs]
readme = "README.md"

[[io.input]]
name = "path"
type = "string"
required = false
description = "Absolute filesystem path."

[[io.output]]
name = "url"
type = "string"
description = "Normalised file:// URL or null when the input is empty."

[deps]
requires = [
  "lcod://tooling/script@1"
]
