schemaVersion = "1.0"
id = "lcod://contract/core/parse/json@1.0.0"
name = "json"
namespace = "contract/core/parse"
version = "1.0.0"
kind = "contract"
summary = "Parse JSON text into a canonical object with optional schema validation."

[tool]
name = "core_parse_json"
description = "Parses JSON strings (optionally from file/stream) and returns structured data."
inputSchema = "schema/json.in.json"
outputSchema = "schema/json.out.json"

[hints]
timeoutMs = 2000

[docs]
readme = "README.md"
