
compose:
  - call: lcod://flow/try@1
    in:
      value: $.value
    out:
      ok: ok
      length: length
    slots:
      body:
        - call: lcod://contract/core/array/length@1
          in:
            items: $.value
          out:
            length: length
        - call: lcod://impl/set@1
          in:
            ok: true
          out:
            ok: ok
      catch:
        - call: lcod://impl/set@1
          in:
            ok: false
            length: 0
          out:
            ok: ok
            length: length
