schemaVersion = "1.0"
id = "lcod://tooling/value/is_array@0.1.0"
name = "is_array"
namespace = "tooling/value"
version = "0.1.0"
kind = "component"

summary = "Check whether a value is an array."

[palette]
category = "Validation"
icon = "mdi:code-brackets"
tags = ["validation"]

[docs]
readme = "README.md"

[[io.input]]
name = "value"
type = "any"
required = false
description = "Value to inspect."

[[io.output]]
name = "ok"
type = "boolean"
description = "True when the value is an array."

[[io.output]]
name = "length"
type = "number"
description = "Length when the value is an array (otherwise 0)."

[deps]
requires = [
  "lcod://tooling/script@1"
]
