schemaVersion = "2.0"
id = "lcod://tooling/value/is_array@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Check whether a value is an array."

[palette]
category = "Validation"
icon = "mdi:code-brackets"
tags = [ "validation" ]

[deps]
requires = [
  "lcod://flow/try@1",
  "lcod://impl/set@1",
  "lcod://contract/core/array/length@1"
]

[inputs.value]
summary = "Value to inspect."
required = false
schema = "{}"

[outputs.ok]
summary = "True when the value is an array."
schema = """
{
  "type": "boolean"
}"""

[outputs.length]
summary = "Length when the value is an array (otherwise 0)."
schema = """
{
  "type": "number"
}"""

[documentation]
body = "Check whether a value is an array."
