schemaVersion = "2.0"
id = "lcod://contract/tooling/array/find_duplicates@1.0.0"
version = "1.0.0"
kind = "contract"
summary = "Return duplicated string values present in an array."

[tool]
name = "tooling_array_find_duplicates"
description = "Extracts duplicate string entries from an array."
inputSchema = "schema/find_duplicates.in.json"
outputSchema = "schema/find_duplicates.out.json"

[documentation]
body = """
Scans the provided array and returns the set of string values that appear more
than once. Non-string entries are ignored."""
