schemaVersion = "2.0"
id = "lcod://core/array/append@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Expose core/array/append@1 as a reusable component."

[palette]
category = "Array"
icon = "mdi:playlist-plus"
tags = [ "array", "append", "core" ]

[deps]
requires = [ "lcod://contract/core/array/append@1" ]

[inputs.array]
summary = "Base array kept immutable by the contract."
required = true
schema = """
{
  "type": "array"
}"""

[inputs.items]
summary = "Items concatenated to the base array."
required = false
schema = """
{
  "type": "array"
}"""

[inputs.item]
summary = "Single item appended after `items` when provided."
required = false
schema = "{}"

[outputs.value]
summary = "Resulting array containing the appended entries."
schema = """
{
  "type": "array"
}"""

[outputs.length]
summary = "Length of the resulting array."
schema = """
{
  "type": "number"
}"""

[documentation]
body = """
Thin wrapper around `core/array/append@1` that exposes the new standard
primitive as an LCOD component."""
