schemaVersion = "2.0"
id = "lcod://impl/net/fetch@1.0.0"
version = "1.0.0"
kind = "function"
summary = "Fetch-based implementation of the http-client contract"

[tool]
name = "http_get"
description = "Perform an HTTP GET-like request"
inputSchema = "schema/http.in.json"
outputSchema = "schema/http.out.json"

[documentation]
body = "Skeleton implementation package for the `contract/net/http-client` contract."
