schemaVersion = "2.0"
id = "lcod://tooling/component/build_artifacts@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Generate README and JSON Schema artefacts from an lcp.toml descriptor."

[deps]
requires = [
  "lcod://tooling/value/default_object@0.1.0",
  "lcod://contract/core/fs/read_file@1",
  "lcod://contract/core/fs/write_file@1",
  "lcod://contract/core/parse/toml@1",
  "lcod://tooling/script@1",
  "lcod://flow/if@1"
]

[inputs.descriptorPath]
summary = "Path to the descriptor (lcp.toml) file."
required = true
schema = """
{
  "type": "string",
  "minLength": 1
}"""

[inputs.write]
summary = "When true (default), write artefacts to disk."
required = false
schema = """
{
  "type": "boolean",
  "default": true
}"""

[inputs.readmePath]
summary = "Override destination path for README.md."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.inputSchemaPath]
summary = "Override destination path for the generated input schema."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.outputSchemaPath]
summary = "Override destination path for the generated output schema."
required = false
schema = """
{
  "type": "string"
}"""

[outputs.descriptor]
summary = "Parsed descriptor object."
schema = """
{
  "type": "object"
}"""

[outputs.readme]
summary = "Generated README content."
schema = """
{
  "type": "string"
}"""

[outputs.inputSchema]
summary = "Generated JSON Schema for component inputs."
schema = """
{
  "type": "object"
}"""

[outputs.outputSchema]
summary = "Generated JSON Schema for component outputs."
schema = """
{
  "type": "object"
}"""

[outputs.readmePath]
summary = "Resolved README output path."
schema = """
{
  "type": "string"
}"""

[outputs.inputSchemaPath]
summary = "Resolved input schema output path."
schema = """
{
  "type": "string"
}"""

[outputs.outputSchemaPath]
summary = "Resolved output schema output path."
schema = """
{
  "type": "string"
}"""

[outputs.readmeWriteResult]
summary = "Result from writing the README (empty when write=false)."
schema = """
{
  "type": "object"
}"""

[outputs.inputSchemaWriteResult]
summary = "Result from writing the input schema (empty when skipped)."
schema = """
{
  "type": "object"
}"""

[outputs.outputSchemaWriteResult]
summary = "Result from writing the output schema (empty when skipped)."
schema = """
{
  "type": "object"
}"""
