schemaVersion = "2.0"
id = "lcod://tooling/string/ensure_trailing_newline@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Ensure a string ends with a trailing newline character."

[palette]
category = "String"
icon = "mdi:format-line-spacing"
tags = [ "string" ]

[deps]
requires = [ "lcod://contract/tooling/string/ensure_trailing_newline@1" ]

[inputs.text]
summary = "Text to normalise."
required = false
schema = """
{
  "type": "string"
}"""

[inputs.newline]
summary = "Newline sequence (defaults to \"\n\")."
required = false
schema = """
{
  "type": "string"
}"""

[outputs.text]
summary = "Normalised text guaranteed to end with the newline sequence."
schema = """
{
  "type": "string"
}"""

[documentation]
body = """
Returns the provided text, adding a newline suffix when it is not already
present. The newline sequence can be customised via the optional `newline`
input (defaults to "\n")."""
