compose:
  - call: lcod://tooling/script@1
    in:
      source: |
        async ({ state }) => {
          const items = Array.isArray(state.items) ? state.items : [];
          if (!items.length) {
            return { head: null, rest: [] };
          }
          const [head, ...rest] = items;
          return {
            head: head ?? null,
            rest
          };
        }
      input:
        items: $.items
    out:
      head: head
      rest: rest
