schemaVersion = "2.0"
id = "lcod://tooling/array/shift@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Extract the first element of an array and return the remaining items."

[deps]
requires = [ "lcod://tooling/script@1" ]

[inputs.items]
summary = "Array to shift from; non-arrays are treated as empty."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.head]
summary = "First element of the array, or null when the array is empty."
schema = "{}"

[outputs.rest]
summary = "Remaining items after removing the first element."
schema = """
{
  "type": "array"
}"""
