schemaVersion = "2.0"
id = "lcod://contract/core/array/length@1.0.0"
version = "1.0.0"
kind = "contract"
summary = "Return the number of elements in an array."

[tool]
name = "core_array_length"
description = "Compute the size of an array and return it as an integer."
inputSchema = "schema/length.in.json"
outputSchema = "schema/length.out.json"

[documentation]
body = "Returns the number of elements contained in the provided array."
