schemaVersion = "2.0"
id = "lcod://tooling/array/concat@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Concatenate two arrays, falling back to empty arrays when inputs are missing."

[deps]
requires = [
  "lcod://tooling/value/default_array@0.1.0",
  "lcod://tooling/array/append@0.1.0",
  "lcod://impl/set@1"
]

[inputs.left]
summary = "Base array (non-arrays are treated as empty)."
required = false
schema = """
{
  "type": "array"
}"""

[inputs.right]
summary = "Array to append (non-arrays are treated as empty)."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.items]
summary = "Concatenated array."
schema = """
{
  "type": "array"
}"""
