schemaVersion = "1.0"
id = "lcod://tooling/array/concat@0.1.0"
name = "array.concat"
namespace = "tooling/array"
version = "0.1.0"
kind = "component"

summary = "Concatenate two arrays, falling back to empty arrays when inputs are missing."

[[io.input]]
name = "left"
type = "array"
description = "Base array (non-arrays are treated as empty)."

[[io.input]]
name = "right"
type = "array"
description = "Array to append (non-arrays are treated as empty)."

[[io.output]]
name = "items"
type = "array"
description = "Concatenated array."

[deps]
requires = [
  "lcod://tooling/value/default_array@0.1.0",
  "lcod://tooling/array/append@0.1.0",
  "lcod://impl/set@1"
]
