compose:
  - call: lcod://env/http_host@0.1.0
    in:
      host: "0.0.0.0"
      port: 8080
      basePath: "/api"
    children:
      projects:
        - call: lcod://project/http_app@0.1.0
          in:
            name: "catalog"
            basePath: "/catalog"
            metadata:
              version: "0.1.0"
          out:
            project: $
          children:
            sequences:
              - call: lcod://tooling/script@1
                in:
                  source: |
                    async () => ({
                      sequences: [
                        {
                          id: 'catalog.listItems',
                          handler: {
                            type: 'script',
                            source: `async () => ({ status: 200, body: [\n  { id: 1, name: 'Keyboard' },\n  { id: 2, name: 'Mouse' }\n] })`
                          }
                        }
                      ]
                    })
                out:
                  sequences: sequences
            apis:
              - call: lcod://tooling/script@1
                in:
                  source: |
                    async () => ({
                      routes: [
                        {
                          method: 'GET',
                          path: '/items',
                          sequenceId: 'catalog.listItems',
                          description: 'List catalog items'
                        }
                      ]
                    })
                out:
                  routes: routes
              - call: lcod://flow/foreach@1
                in:
                  list: $.routes
                children:
                  body:
                    - call: lcod://http/api_route@0.1.0
                      in:
                        method: $slot.item.method
                        path: $slot.item.path
                        sequenceId: $slot.item.sequenceId
                        description: $slot.item.description
                      out:
                        route: route
                collectPath: $.route
                out:
                  routes: results
    out:
      host: $
