schemaVersion = "1.0"
id = "lcod://contract/core/stream/read@1.0.0"
name = "read"
namespace = "contract/core/stream"
version = "1.0.0"
kind = "contract"
summary = "Read the next chunk from a stream handle."

[tool]
name = "core_stream_read"
description = "Pulls data from a stream handle with optional decoding and timeout."
inputSchema = "schema/read.in.json"
outputSchema = "schema/read.out.json"

[hints]
timeoutMs = 5000

[docs]
readme = "README.md"
