schemaVersion = "2.0"
id = "lcod://tooling/fs/write_if_changed@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Write text to a file only when the contents change."

[palette]
category = "Filesystem"
icon = "mdi:file-document-edit"
tags = [ "filesystem", "write" ]

[deps]
requires = [ "lcod://contract/tooling/fs/write_if_changed@1" ]

[inputs.path]
summary = "Destination file path."
required = true
schema = """
{
  "type": "string",
  "minLength": 1
}"""

[inputs.content]
summary = "Content to write."
required = false
schema = "{}"

[inputs.encoding]
summary = "Text encoding used to read and write (defaults to \"utf-8\")."
required = false
schema = """
{
  "type": "string"
}"""

[outputs.changed]
summary = "True when the file was written because the content changed."
schema = """
{
  "type": "boolean"
}"""

[documentation]
body = """
Normalises the provided content to a string, compares it with the current file
contents (using the requested encoding) and writes the file only when the data
changes. The component reports whether the file was modified."""
