schemaVersion = "2.0"
id = "lcod://contract/net/http-client@1.0.0"
version = "1.0.0"
kind = "contract"
summary = "HTTP client contract: GET-like call"

[tool]
name = "http_get"
description = "Perform an HTTP GET-like request"
inputSchema = "schema/http.in.json"
outputSchema = "schema/http.out.json"

[documentation]
body = "Minimal HTTP client contract describing a GET-like call (input: url/headers/timeout; output: status/body/headers)."
