schemaVersion = "2.0"
id = "lcod://tooling/array/length@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Return the number of items in an array."

[palette]
category = "Array"
icon = "mdi:numeric"
tags = [ "array", "metrics" ]

[deps]
requires = [ "lcod://axiom/array/length@1" ]

[inputs.items]
summary = "Array to measure (non-arrays yield length 0)."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.length]
summary = "Number of elements in the array."
schema = """
{
  "type": "number"
}"""

[documentation]
body = "Return the number of items in an array."
