schemaVersion = "2.0"
id = "lcod://tooling/array/compact@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Remove null and undefined entries from an array."

[palette]
category = "Array"
icon = "mdi:filter-variant"
tags = [ "array", "cleanup" ]

[deps]
requires = [ "lcod://contract/tooling/array/compact@1" ]

[inputs.items]
summary = "Array that may contain null or undefined values."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.values]
summary = "Array without null/undefined entries."
schema = """
{
  "type": "array"
}"""

[documentation]
body = "Remove null and undefined entries from an array."
