schemaVersion = "1.0"
id = "lcod://core/string/format@0.1.0"
name = "format"
namespace = "core/string"
version = "0.1.0"
kind = "component"

summary = "Expose core/string/format@1 as an LCOD component."

[palette]
category = "String"
icon = "mdi:code-braces"
tags = ["string", "format", "core"]

[docs]
readme = "README.md"

[[io.input]]
name = "template"
type = "string"
required = true
description = "Template containing placeholders."

[[io.input]]
name = "values"
type = "object"
required = false
description = "Dictionary of values injected into the template."

[[io.input]]
name = "fallback"
type = "string"
required = false
description = "Default replacement when a placeholder cannot be resolved."

[[io.input]]
name = "missingPolicy"
type = "string"
required = false
description = "How to handle missing placeholders (`ignore` or `error`)."

[[io.output]]
name = "value"
type = "string"
description = "Rendered string."

[[io.output]]
name = "missing"
type = "array"
description = "Placeholders that were not resolved (when `missingPolicy` is `ignore`)."

[[io.output]]
name = "error"
type = "object"
description = "Optional structured error when `missingPolicy = \"error\"`."

[deps]
requires = [
  "lcod://contract/core/string/format@1"
]
