compose:
  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.queue
    out:
      initialQueue: resolved
  - call: lcod://tooling/queue/bfs@0.1.0
    in:
      items: $.initialQueue
      state:
        contributions: []
        context:
          downloadsRoot: $.downloadsRoot
          sourcesBaseDir: $.sourcesBaseDir
          defaultEntrypoint: $.defaultEntrypoint
          basePriority: $.basePriority
    out:
      traversalState: state
      traversalVisited: visited
      traversalWarnings: warnings
    slots:
      key:
        - call: lcod://tooling/value/is_string_nonempty@0.1.0
          in:
            value: $slot.item.id
          out:
            pointerHasId: ok
        - call: lcod://core/string/format@0.1.0
          in:
            template: id:{id}
            values:
              id: $slot.item.id
          out:
            keyFromId: value
        - call: lcod://tooling/json/stable_stringify@0.1.0
          in:
            value: $slot.item
          out:
            serializedPointer: text
            serializeWarning: warning
        - call: lcod://tooling/hash/to_key@0.1.0
          in:
            text: $.serializedPointer
            prefix: "json:"
          out:
            hashedKey: key
        - call: lcod://flow/if@1
          in:
            cond: $.pointerHasId
          out:
            key: key
          slots:
            then:
              - call: lcod://impl/set@1
                in:
                  key: $.keyFromId
                out:
                  key: key
            else:
              - call: lcod://impl/set@1
                in:
                  key: $.hashedKey
                out:
                  key: key
      process:
        - call: lcod://tooling/value/default_object@0.1.0
          in:
            value: $slot.state
          out:
            currentState: resolved
        - call: lcod://tooling/value/default_object@0.1.0
          in:
            value: $.currentState.context
          out:
            context: resolved
        - call: lcod://tooling/value/default_array@0.1.0
          in:
            value: $.currentState.contributions
          out:
            baseContributions: resolved
        - call: lcod://impl/set@1
          in:
            currentPointer: $slot.item
          out:
            currentPointer: currentPointer
        - call: lcod://tooling/registry_sources/process_pointer@0.1.0
          in:
            pointer: $slot.item
            downloadsRoot: $.context.downloadsRoot
            defaultEntrypoint: $.context.defaultEntrypoint
            basePriority: $.context.basePriority
          out:
            processedEntry: entry
            pointerChildren: children
            processWarnings: warnings
        - call: lcod://tooling/value/default_array@0.1.0
          in:
            value: $.pointerChildren
          out:
            pointerChildren: resolved
        - call: lcod://flow/foreach@1
          in:
            list: $.pointerChildren
          collectPath: $.normalized
          out:
            normalizedChildren: results
          slots:
            body:
              - call: lcod://tooling/value/is_string_nonempty@0.1.0
                in:
                  value: $slot.item.baseDir
                out:
                  childHasBaseDir: ok
              - call: lcod://flow/if@1
                in:
                  cond: $.childHasBaseDir
                out:
                  pointerBaseDir: pointerBaseDir
                slots:
                  then:
                    - call: lcod://impl/set@1
                      in:
                        pointerBaseDir: $slot.item.baseDir
                      out:
                        pointerBaseDir: pointerBaseDir
                  else:
                    - call: lcod://impl/set@1
                      in:
                        pointerBaseDir: $.currentPointer.baseDir
                      out:
                        pointerBaseDir: pointerBaseDir
              - call: lcod://tooling/registry_sources/normalize_pointer@0.1.0
                in:
                  entry: $slot.item
                  inherited: $.currentPointer
                  baseDir: $.pointerBaseDir
                  sourcesBaseDir: $.context.sourcesBaseDir
                  defaultEntrypoint: $.context.defaultEntrypoint
                  basePriority: $.context.basePriority
                  catalogueBaseDir: $.pointerBaseDir
                out:
                  childPointer: pointer
                  normalizeWarnings: warnings
              - call: lcod://impl/set@1
                in:
                  normalized:
                    pointer: $.childPointer
                    warnings: $.normalizeWarnings
                out:
                  normalized: normalized
        - call: lcod://tooling/registry_sources/partition_normalized@0.1.0
          in:
            entries: $.normalizedChildren
          out:
            normalizedPointers: pointers
            normalizationWarnings: warnings
        - call: lcod://tooling/value/default_array@0.1.0
          in:
            value: $.normalizedPointers
          out:
            normalizedPointers: resolved
        - call: lcod://tooling/value/default_array@0.1.0
          in:
            value: $.processWarnings
          out:
            processWarnings: resolved
        - call: lcod://tooling/value/default_array@0.1.0
          in:
            value: $.normalizationWarnings
          out:
            normalizationWarnings: resolved
        - call: lcod://tooling/registry_sources/build_inline_entry@0.1.0
          in:
            pointer: $slot.item
            entry: $.processedEntry
          out:
            contribution: contribution
        - call: lcod://tooling/value/is_object@0.1.0
          in:
            value: $.contribution
          out:
            hasContribution: ok
        - call: lcod://flow/if@1
          in:
            cond: $.hasContribution
          out:
            contributionBatch: contributionBatch
          slots:
            then:
              - call: lcod://tooling/array/append@0.1.0
                in:
                  items: []
                  value: $.contribution
                out:
                  contributionBatch: items
        - call: lcod://tooling/value/default_array@0.1.0
          in:
            value: $.contributionBatch
          out:
            contributionBatch: resolved
        - call: lcod://tooling/array/append@0.1.0
          in:
            items: $.baseContributions
            values: $.contributionBatch
          out:
            updatedContributions: items
        - call: lcod://tooling/array/append@0.1.0
          in:
            items: $.processWarnings
            values: $.normalizationWarnings
          out:
            combinedWarnings: items
        - call: lcod://impl/set@1
          in:
            state:
              contributions: $.updatedContributions
              context: $.context
            children: $.normalizedPointers
            warnings: $.combinedWarnings
            slots: $.normalizedPointers
          out:
            state: state
            children: children
            warnings: warnings
            slots: children
  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.traversalState.contributions
    out:
      contributions: resolved
  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.traversalWarnings
    out:
      warnings: resolved
