compose:
  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.queue
    out:
      currentQueue: resolved

  - call: lcod://tooling/array/length@0.1.0
    in:
      items: $.currentQueue
    out:
      queueLength: length

  - call: lcod://flow/if@1
    in:
      cond: $.queueLength
    children:
      then:
        - call: lcod://tooling/array/shift@0.1.0
          in:
            items: $.currentQueue
          out:
            headPointer: head
            restQueue: rest
        - call: lcod://flow/if@1
          in:
            cond: $.headPointer
          children:
            then:
              - call: lcod://tooling/registry_sources/process_pointer@0.1.0
                in:
                  pointer: $.headPointer
                  downloadsRoot: $.downloadsRoot
                  defaultEntrypoint: $.defaultEntrypoint
                  basePriority: $.basePriority
                out:
                  processedEntry: entry
                  pointerChildren: children
                  processWarnings: warnings
              - call: lcod://tooling/value/default_array@0.1.0
                in:
                  value: $.pointerChildren
                out:
                  pointerChildren: resolved

              - call: lcod://flow/foreach@1
                in:
                  list: $.pointerChildren
                children:
                  body:
                    - call: lcod://tooling/value/is_string_nonempty@0.1.0
                      in:
                        value: $slot.item.baseDir
                      out:
                        childHasBaseDir: ok
                    - call: lcod://flow/if@1
                      in:
                        cond: $.childHasBaseDir
                      children:
                        then:
                          - call: lcod://impl/set@1
                            in:
                              pointerBaseDir: $slot.item.baseDir
                            out:
                              pointerBaseDir: pointerBaseDir
                        else:
                          - call: lcod://impl/set@1
                            in:
                              pointerBaseDir: $.headPointer.baseDir
                            out:
                              pointerBaseDir: pointerBaseDir
                      out:
                        pointerBaseDir: pointerBaseDir
                    - call: lcod://tooling/registry_sources/normalize_pointer@0.1.0
                      in:
                        entry: $slot.item
                        inherited: $.headPointer
                        baseDir: $.pointerBaseDir
                        sourcesBaseDir: $.sourcesBaseDir
                        defaultEntrypoint: $.defaultEntrypoint
                        basePriority: $.basePriority
                        catalogueBaseDir: $.pointerBaseDir
                      out:
                        childPointer: pointer
                        normalizeWarnings: warnings
                    - call: lcod://impl/set@1
                      in:
                        normalized:
                          pointer: $.childPointer
                          warnings: $.normalizeWarnings
                      out:
                        normalized: normalized
                collectPath: $.normalized
                out:
                  normalizedChildren: results

              - call: lcod://tooling/registry_sources/partition_normalized@0.1.0
                in:
                  entries: $.normalizedChildren
                out:
                  normalizedPointers: pointers
                  normalizationWarnings: warnings
              - call: lcod://tooling/registry_sources/build_inline_entry@0.1.0
                in:
                  pointer: $.headPointer
                  entry: $.processedEntry
                out:
                  contribution: contribution
              - call: lcod://tooling/value/is_object@0.1.0
                in:
                  value: $.contribution
                out:
                  hasContribution: ok
              - call: lcod://flow/if@1
                in:
                  cond: $.hasContribution
                children:
                  then:
                    - call: lcod://tooling/array/append@0.1.0
                      in:
                        items: []
                        value: $.contribution
                      out:
                        contributionsBatch: items
                out:
                  contributionsBatch: contributionsBatch

              - call: lcod://tooling/value/default_array@0.1.0
                in:
                  value: $.processWarnings
                out:
                  normalizedProcessWarnings: resolved

              - call: lcod://tooling/value/default_array@0.1.0
                in:
                  value: $.normalizationWarnings
                out:
                  normalizedNormalizationWarnings: resolved

              - call: lcod://tooling/array/append@0.1.0
                in:
                  items: $.normalizedProcessWarnings
                  values: $.normalizedNormalizationWarnings
                out:
                  accumulatedWarnings: items

              - call: lcod://tooling/array/append@0.1.0
                in:
                  items: $.restQueue
                  values: $.normalizedPointers
                out:
                  nextQueue: items

              - call: lcod://tooling/registry_sources/collect_queue@0.1.0
                in:
                  queue: $.nextQueue
                  downloadsRoot: $.downloadsRoot
                  sourcesBaseDir: $.sourcesBaseDir
                  defaultEntrypoint: $.defaultEntrypoint
                  basePriority: $.basePriority
                out:
                  tailContributions: contributions
                  tailWarnings: warnings
              - call: lcod://tooling/value/default_array@0.1.0
                in:
                  value: $.tailContributions
                out:
                  tailContributions: resolved

              - call: lcod://tooling/value/default_array@0.1.0
                in:
                  value: $.tailWarnings
                out:
                  tailWarnings: resolved

              - call: lcod://tooling/value/default_array@0.1.0
                in:
                  value: $.contributionsBatch
                out:
                  contributionsBatch: resolved

              - call: lcod://tooling/array/append@0.1.0
                in:
                  items: $.contributionsBatch
                  values: $.tailContributions
                out:
                  contributions: items

              - call: lcod://tooling/array/append@0.1.0
                in:
                  items: $.accumulatedWarnings
                  values: $.tailWarnings
                out:
                  warnings: items

            else:
              - call: lcod://tooling/registry_sources/collect_queue@0.1.0
                in:
                  queue: $.restQueue
                  downloadsRoot: $.downloadsRoot
                  sourcesBaseDir: $.sourcesBaseDir
                  defaultEntrypoint: $.defaultEntrypoint
                  basePriority: $.basePriority
                out:
                  contributions: contributions
                  warnings: warnings
          out:
            contributions: contributions
            warnings: warnings
      else:
        - call: lcod://impl/set@1
          in:
            contributions: []
            warnings: []
          out:
            contributions: contributions
            warnings: warnings
    out:
      contributions: contributions
      warnings: warnings
