schemaVersion = "2.0"
id = "lcod://contract/core/array/push@1.0.0"
version = "1.0.0"
kind = "contract"
summary = "Append a value to an array and return the new collection."

[tool]
name = "core_array_push"
description = "Append a value to an array, returning the new array and its length."
inputSchema = "schema/push.in.json"
outputSchema = "schema/push.out.json"

[documentation]
body = "Appends a single value to the end of an array and returns the updated collection."
