schemaVersion = "1.0"
id = "lcod://tooling/value/is_string_nonempty@0.1.0"
name = "is_string_nonempty"
namespace = "tooling/value"
version = "0.1.0"
kind = "component"

summary = "Check whether a value is a non-empty string."

[palette]
category = "Validation"
icon = "mdi:format-letter-case"
tags = ["validation"]

[docs]
readme = "README.md"

[[io.input]]
name = "value"
type = "any"
required = false
description = "Value to inspect."

[[io.output]]
name = "ok"
type = "boolean"
description = "True when the value is a string with length greater than zero."

[deps]
requires = [
  "lcod://tooling/script@1"
]
