schemaVersion = "2.0"
id = "lcod://tooling/value/is_string_nonempty@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Check whether a value is a non-empty string."

[palette]
category = "Validation"
icon = "mdi:format-letter-case"
tags = [ "validation" ]

[deps]
requires = [
  "lcod://flow/try@1",
  "lcod://flow/if@1",
  "lcod://impl/set@1",
  "lcod://core/string/format@0.1.0"
]

[inputs.value]
summary = "Value to inspect."
required = false
schema = "{}"

[outputs.ok]
summary = "True when the value is a string with length greater than zero."
schema = """
{
  "type": "boolean"
}"""

[documentation]
body = "Check whether a value is a non-empty string."
