compose:
  - call: lcod://contract/tooling/fs/read_optional@1
    in:
      path: $.path
      encoding: $.encoding
      fallback: $.fallback
      warningMessage: $.warningMessage
    out:
      text: text
      exists: exists
      warning: warning
