schemaVersion = "1.0"
id = "lcod://tooling/registry_sources/prepare_env@0.1.0"
name = "prepare_env"
namespace = "tooling/registry_sources"
version = "0.1.0"
kind = "component"

summary = "Resolve project, cache and downloads directories used by registry source resolution."

[palette]
category = "Registry"
icon = "mdi:folder-cog"
tags = ["registry", "paths"]

[docs]
readme = "README.md"

[[io.input]]
name = "projectPath"
type = "string"
required = false
description = "Optional project root path (relative paths are resolved from cwd)."

[[io.input]]
name = "cacheDir"
type = "string"
required = false
description = "Optional cache directory (defaults to `<project>/.lcod/cache`)."

[[io.input]]
name = "cwd"
type = "string"
required = false
description = "Explicit working directory used when projectPath is relative."

[[io.output]]
name = "projectRoot"
type = "string"
description = "Resolved project root directory."

[[io.output]]
name = "cacheDir"
type = "string"
description = "Resolved cache directory path."

[[io.output]]
name = "downloadsRoot"
type = "string"
description = "Directory dedicated to downloaded catalogues."

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://axiom/path/join@1"
]
