schemaVersion = "2.0"
id = "lcod://tooling/array/find_duplicates@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Return duplicated string values present in an array."

[palette]
category = "Array"
icon = "mdi:alert-octagon-outline"
tags = [ "array" ]

[deps]
requires = [ "lcod://contract/tooling/array/find_duplicates@1" ]

[inputs.items]
summary = "Array to inspect."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.duplicates]
summary = "Array of duplicated string values."
schema = """
{
  "type": "array",
  "items": { "type": "string" }
}"""

[documentation]
body = """
Scans the provided array and returns the set of string values that appear more
than once. Non-string entries are ignored."""
