schemaVersion = "1.0"
id = "lcod://contract/core/object/set@1.0.0"
name = "set"
namespace = "contract/core/object"
version = "1.0.0"
kind = "contract"
summary = "Set a nested value on an object and return the updated structure."

[tool]
name = "core_object_set"
description = "Assigns a value at the provided path, optionally cloning the object."
inputSchema = "schema/set.in.json"
outputSchema = "schema/set.out.json"

[docs]
readme = "README.md"
