schemaVersion = "2.0"
id = "lcod://contract/core/object/set@1.0.0"
version = "1.0.0"
kind = "contract"
summary = "Set a nested value on an object and return the updated structure."

[tool]
name = "core_object_set"
description = "Assigns a value at the provided path, optionally cloning the object."
inputSchema = "schema/set.in.json"
outputSchema = "schema/set.out.json"

[documentation]
body = "Assigns a value to a nested path within an object and returns the updated structure. The contract supports immutable updates as well as in-place mutation."
