schemaVersion = "1.0"
id = "lcod://http/api_route@0.1.0"
name = "api_route"
namespace = "http"
version = "0.1.0"
kind = "contract"
summary = "Route descriptor binding an HTTP method/path to a handler sequence."

[tool]
name = "api_route"
description = "Describe a single HTTP endpoint and its handler."
inputSchema = "schema/api_route.in.json"
outputSchema = "schema/api_route.out.json"

[docs]
readme = "README.md"
