schemaVersion = "1.0"
id = "lcod://contract/core/array/append@1.0.0"
name = "append"
namespace = "contract/core/array"
version = "1.0.0"
kind = "contract"
summary = "Concatenate arrays or append a single value without mutating the input."

[tool]
name = "core_array_append"
description = "Append items to an array and return the resulting array."
inputSchema = "schema/append.in.json"
outputSchema = "schema/append.out.json"

[docs]
readme = "README.md"
