schemaVersion = "2.0"
id = "lcod://contract/core/array/append@1.0.0"
version = "1.0.0"
kind = "contract"
summary = "Concatenate arrays or append a single value without mutating the input."

[tool]
name = "core_array_append"
description = "Append items to an array and return the resulting array."
inputSchema = "schema/append.in.json"
outputSchema = "schema/append.out.json"

[documentation]
body = """
Concatenates an existing array with additional values. This contract always
returns a new array and leaves the inputs unchanged."""
