schemaVersion = "2.0"
id = "lcod://contract/core/json/encode@1.0.0"
version = "1.0.0"
kind = "contract"
summary = "Serialize structured data into JSON text."

[tool]
name = "core_json_encode"
description = "Serialize LCOD data into JSON text with deterministic output."
inputSchema = "schema/encode.in.json"
outputSchema = "schema/encode.out.json"

[documentation]
body = """
Serializes structured data into JSON text with deterministic output. Implementations
must guarantee UTF-8 output and optionally support pretty-printing and key sorting."""
