schemaVersion = "1.0"
id = "lcod://tooling/registry_sources/resolve@0.1.0"
name = "resolve"
namespace = "tooling/registry_sources"
version = "0.1.0"
kind = "component"

summary = "Load registry catalogues defined in sources.json and produce inline registry sources."

[palette]
category = "Registry"
icon = "mdi:source-branch"
tags = ["registry", "catalogue"]

[docs]
readme = "README.md"

[[io.input]]
name = "projectPath"
type = "string"
required = false
description = "Project root used to resolve relative pointers."

[[io.input]]
name = "cacheDir"
type = "string"
required = false
description = "Cache directory root (defaults to project/.lcod/cache)."

[[io.input]]
name = "sourcesPath"
type = "string"
required = false
description = "Explicit path to sources.json."

[[io.input]]
name = "sourcesText"
type = "string"
required = false
description = "When provided, skip reading from disk and reuse the given JSON payload."

[[io.input]]
name = "defaultSourcesSpec"
type = "object"
required = false
description = "Default sources specification used when the file is missing."

[[io.input]]
name = "cwd"
type = "string"
required = false
description = "Working directory fallback when projectPath is not provided."

[[io.output]]
name = "registrySources"
type = "array"
description = "Inline registry source entries consumed by the resolver."

[[io.output]]
name = "warnings"
type = "array"
description = "Warning messages collected during resolution."

[[io.output]]
name = "sourcesPath"
type = "string"
description = "Final location or label of the sources specification."

[[io.output]]
name = "projectRoot"
type = "string"
description = "Resolved project root."

[[io.output]]
name = "cacheDir"
type = "string"
description = "Resolved cache directory root."

[[io.output]]
name = "downloadsRoot"
type = "string"
description = "Directory used to store downloaded catalogues."

[[io.output]]
name = "sourcesConfig"
type = "object"
description = "Parsed sources specification."

[deps]
requires = [
  "lcod://tooling/registry_sources/prepare_env@0.1.0",
  "lcod://tooling/registry_sources/load_config@0.1.0",
  "lcod://tooling/registry_sources/collect_entries@0.1.0",
  "lcod://tooling/array/append@0.1.0",
  "lcod://flow/if@1",
  "lcod://impl/set@1"
]
