schemaVersion = "1.0"
id = "lcod://contract/core/hash/sha256@1.0.0"
name = "sha256"
namespace = "contract/core/hash"
version = "1.0.0"
kind = "contract"
summary = "Compute the SHA-256 digest of data provided inline or via stream/file handle."

[tool]
name = "core_hash_sha256"
description = "Returns a SHA-256 digest with hex/base64 encodings and optional size information."
inputSchema = "schema/sha256.in.json"
outputSchema = "schema/sha256.out.json"

[hints]
timeoutMs = 5000

[docs]
readme = "README.md"
