compose:
  - call: lcod://flow/foreach@1
    in:
      list: $.numbers
    collectPath: $.val
    out:
      results: results
    slots:
      body:
        - call: lcod://impl/echo@1
          in:
            value: $slot.item
          out:
            val: val
      else: []
