schemaVersion = "2.0"
id = "lcod://flow/foreach_demo@0.1.0"
version = "0.1.0"
kind = "function"
summary = "Demo foreach composition collecting values with else-slot."

[deps]
requires = [
  "lcod://flow/foreach@1",
  "lcod://flow/continue@1",
  "lcod://flow/break@1",
  "lcod://impl/echo@1"
]

[tool]
name = "foreach_demo"
description = "Iterate numbers, collect values; else provides default."
inputSchema = "schema/foreach_demo.in.json"
outputSchema = "schema/foreach_demo.out.json"

[documentation]
body = """
Minimal demo to exercise `lcod://flow/foreach@1` with value collection
via `meta.collectPath`. Else-slot runs when the list is empty.

Notes
- Body echoes each item so `collectPath` can pick it up.
- Else-slot runs if the list is empty (results stays empty here).
- To run, register flow blocks (`foreach` and optionally `continue`/`break`) and a simple `impl/echo` in your runner.

Suggested `impl/echo` (pseudo):
`echo(ctx, { value }) => ({ val: value })`

Sample input
`{ "numbers": [1, 2, 3, 8, 9] }`

Expected output
`{ "results": [1, 2, 3, 8, 9] }`"""
