schemaVersion = "1.0"
id = "lcod://flow/foreach_demo@0.1.0"
name = "foreach_demo"
namespace = "flow"
version = "0.1.0"
kind = "function"
summary = "Demo foreach composition collecting values with else-slot."

[tool]
name = "foreach_demo"
description = "Iterate numbers, collect values; else provides default."
inputSchema = "schema/foreach_demo.in.json"
outputSchema = "schema/foreach_demo.out.json"

[deps]
requires = [
  "lcod://flow/foreach@1",
  "lcod://flow/continue@1",
  "lcod://flow/break@1",
  "lcod://impl/echo@1"
]

[docs]
readme = "README.md"

