schemaVersion = "1.0"
id = "lcod://contract/core/fs/read-file@1.0.0"
name = "read-file"
namespace = "contract/core/fs"
version = "1.0.0"
kind = "contract"
summary = "Read file contents from the local filesystem."

[tool]
name = "fs_read_file"
description = "Read a file from the filesystem, optionally decoding text."
inputSchema = "schema/read_file.in.json"
outputSchema = "schema/read_file.out.json"

[hints]
timeoutMs = 5000

[docs]
readme = "README.md"
