schemaVersion = "2.0"
id = "lcod://tooling/hash/sha256_base64@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Compute a SHA-256 checksum and return it in base64 format."

[palette]
category = "Tooling"
icon = "mdi:lock"
tags = [ "hash", "sha256" ]

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://contract/core/hash/sha256@1"
]

[inputs.data]
summary = "Input data (UTF-8 string)."
required = false
schema = """
{
  "type": "string"
}"""

[outputs.hex]
summary = "SHA-256 digest in hexadecimal (lowercase)."
schema = """
{
  "type": "string"
}"""

[outputs.base64]
summary = "SHA-256 digest encoded in base64."
schema = """
{
  "type": "string"
}"""

[documentation]
body = """
Compute a SHA-256 checksum for a UTF-8 string and expose both the hexadecimal
and base64 representations."""
