schemaVersion = "1.0"
id = "lcod://tooling/hash/sha256_base64@0.1.0"
name = "sha256_base64"
namespace = "tooling/hash"
version = "0.1.0"
kind = "component"

summary = "Compute a SHA-256 checksum and return it in base64 format."

[palette]
category = "Tooling"
icon = "mdi:lock"
tags = ["hash", "sha256"]

[docs]
readme = "README.md"

[[io.input]]
name = "data"
type = "string"
required = false
description = "Input data (UTF-8 string)."

[[io.output]]
name = "hex"
type = "string"
description = "SHA-256 digest in hexadecimal (lowercase)."

[[io.output]]
name = "base64"
type = "string"
description = "SHA-256 digest encoded in base64."

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://contract/core/hash/sha256@1"
]
