compose:
  - call: lcod://impl/set@1
    in:
      defaultSourcesSpec:
        schema: "lcod-resolver/sources@1"
        sources:
          - id: "lcod-official"
            priority: 50
            entrypoint:
              type: "https"
              url: "https://raw.githubusercontent.com/lcod-team/lcod-registry/main/catalogues.json"
    out:
      defaultSourcesSpec: defaultSourcesSpec

  - call: lcod://tooling/registry_sources/resolve@0.1.0
    in:
      projectPath: $.projectPath
      cacheDir: $.cacheDir
      sourcesPath: $.sourcesPath
      defaultSourcesSpec: $.defaultSourcesSpec
    out:
      registrySources: registrySources
      warnings: warnings
      sourcesPath: sourcesPath
