compose:
  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.items
    out:
      sourceItems: resolved
  - call: lcod://flow/foreach@1
    in:
      list: $.sourceItems
    children:
      body:
        - call: lcod://tooling/value/is_object@0.1.0
          in:
            value: $slot.item
          out:
            isObject: ok
        - call: lcod://flow/if@1
          in:
            cond: $.isObject
          children:
            then:
              - call: lcod://impl/set@1
                in:
                  candidate: $slot.item
                out:
                  candidate: candidate
            else:
              - call: lcod://impl/set@1
                in:
                  candidate: null
                out:
                  candidate: candidate
          out:
            candidate: candidate
          slots:
            then:
              - call: lcod://impl/set@1
                in:
                  candidate: $slot.item
                out:
                  candidate: candidate
            else:
              - call: lcod://impl/set@1
                in:
                  candidate: null
                out:
                  candidate: candidate
    collectPath: $.candidate
    out:
      filteredCandidates: results
    slots:
      body:
        - call: lcod://tooling/value/is_object@0.1.0
          in:
            value: $slot.item
          out:
            isObject: ok
        - call: lcod://flow/if@1
          in:
            cond: $.isObject
          children:
            then:
              - call: lcod://impl/set@1
                in:
                  candidate: $slot.item
                out:
                  candidate: candidate
            else:
              - call: lcod://impl/set@1
                in:
                  candidate: null
                out:
                  candidate: candidate
          out:
            candidate: candidate
          slots:
            then:
              - call: lcod://impl/set@1
                in:
                  candidate: $slot.item
                out:
                  candidate: candidate
            else:
              - call: lcod://impl/set@1
                in:
                  candidate: null
                out:
                  candidate: candidate
  - call: lcod://tooling/array/compact@0.1.0
    in:
      items: $.filteredCandidates
    out:
      filteredItems: values
  - call: lcod://impl/set@1
    in:
      items: $.filteredItems
    out:
      items: items
