schemaVersion = "1.0"
id = "lcod://tooling/array/filter_objects@0.1.0"
name = "array.filter_objects"
namespace = "tooling/array"
version = "0.1.0"
kind = "component"

summary = "Filter an array to keep only plain objects."

[[io.input]]
name = "items"
type = "array"
description = "Array potentially containing objects."

[[io.output]]
name = "items"
type = "array"
description = "Filtered array containing only non-null objects."

[deps]
requires = [
  "lcod://tooling/value/default_array@0.1.0",
  "lcod://tooling/value/is_object@0.1.0",
  "lcod://flow/if@1",
  "lcod://flow/foreach@1",
  "lcod://tooling/array/compact@0.1.0",
  "lcod://impl/set@1"
]
