schemaVersion = "2.0"
id = "lcod://tooling/array/filter_objects@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Filter an array to keep only plain objects."

[deps]
requires = [
  "lcod://tooling/value/default_array@0.1.0",
  "lcod://tooling/value/is_object@0.1.0",
  "lcod://flow/if@1",
  "lcod://flow/foreach@1",
  "lcod://tooling/array/compact@0.1.0",
  "lcod://impl/set@1"
]

[inputs.items]
summary = "Array potentially containing objects."
required = false
schema = """
{
  "type": "array"
}"""

[outputs.items]
summary = "Filtered array containing only non-null objects."
schema = """
{
  "type": "array"
}"""
