schemaVersion = "1.0"
id = "lcod://tooling/registry/source/load@0.1.0"
name = "registry_source_load"
namespace = "tooling/registry"
version = "0.1.0"
kind = "function"
summary = "Load registry sources from resolver configuration (paths, JSONL, inline) into normalized JSONL streams."

[tool]
name = "Load Registry Sources"
description = "Reads registry sources (path/jsonl/inline) from the resolver config, loads packages.jsonl and registry defaults, and returns normalized streams."
inputSchema = "schema/source_load.in.json"
outputSchema = "schema/source_load.out.json"

[deps]
requires = [
  "lcod://tooling/script@1"
]

[docs]
readme = "README.md"
