schemaVersion = "2.0"
id = "lcod://core/json/encode@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Expose core/json/encode@1 as an LCOD component."

[palette]
category = "JSON"
icon = "mdi:code-json"
tags = [ "json", "encode", "core" ]

[deps]
requires = [ "lcod://contract/core/json/encode@1" ]

[inputs.value]
summary = "Data to encode as JSON."
required = true
schema = "{}"

[inputs.space]
summary = "Indentation width (0-10)."
required = false
schema = """
{
  "type": "number"
}"""

[inputs.sortKeys]
summary = "Sort object keys alphabetically."
required = false
schema = """
{
  "type": "boolean"
}"""

[inputs.asciiOnly]
summary = "Escape non-ASCII characters."
required = false
schema = """
{
  "type": "boolean"
}"""

[outputs.text]
summary = "JSON representation."
schema = """
{
  "type": "string"
}"""

[outputs.bytes]
summary = "Number of UTF-8 bytes emitted."
schema = """
{
  "type": "number"
}"""

[outputs.error]
summary = "Structured error when encoding fails."
schema = """
{
  "type": "object"
}"""

[documentation]
body = "Wrapper over `core/json/encode@1` that serialises structured data to JSON text."
