schemaVersion = "2.0"
id = "lcod://tooling/array/append@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Append optional arrays and/or a single value to the provided items."

[palette]
category = "Array"
icon = "mdi:plus-box-outline"
tags = [ "array", "mutation" ]

[deps]
requires = [ "lcod://contract/tooling/array/append@1" ]

[inputs.items]
summary = "Source array (defaults to an empty list)."
required = false
schema = """
{
  "type": "array"
}"""

[inputs.values]
summary = "Additional items appended before `value`."
required = false
schema = """
{
  "type": "array"
}"""

[inputs.value]
summary = "Single value appended when provided."
required = false
schema = "{}"

[outputs.items]
summary = "Updated array including the appended value."
schema = """
{
  "type": "array"
}"""

[outputs.length]
summary = "Length of the array after the append operation."
schema = """
{
  "type": "number"
}"""

[documentation]
body = """
Append optional arrays and/or a single value to the provided list without
mutating the original array."""
