schemaVersion = "2.0"
id = "lcod://contract/tooling/fs/read_optional@1.0.0"
version = "1.0.0"
kind = "contract"
summary = "Read a text file when it exists, falling back to default content."

[tool]
name = "tooling_fs_read_optional"
description = "Attempts to read a file and reports whether it exists."
inputSchema = "schema/read_optional.in.json"
outputSchema = "schema/read_optional.out.json"

[documentation]
body = """
Reads a text file with the supplied encoding. When the file is missing, the
contract returns the provided fallback text (if any) and marks `exists = false`.
Any warning message supplied via `warningMessage` is propagated on missing
files or read errors.
"""
