schemaVersion = "1.0"
id = "lcod://tooling/registry/select@0.1.0"
name = "registry_select"
namespace = "tooling/registry"
version = "0.1.0"
kind = "function"
summary = "Select a registry entry matching a component id and semver range."

[tool]
name = "Select Registry Entry"
description = "Given registry packages and a component identifier, selects the best matching entry according to semantic version rules."
inputSchema = "schema/select.in.json"
outputSchema = "schema/select.out.json"

[deps]
requires = [
  "lcod://tooling/script@1"
]

[docs]
readme = "README.md"
