schemaVersion = "2.0"
id = "lcod://tooling/registry/select@0.1.0"
version = "0.1.0"
kind = "function"
summary = "Select a registry entry matching a component id and semver range."

[deps]
requires = [ "lcod://tooling/script@1" ]

[tool]
name = "Select Registry Entry"
description = "Given registry packages and a component identifier, selects the best matching entry according to semantic version rules."
inputSchema = "schema/select.in.json"
outputSchema = "schema/select.out.json"

[documentation]
body = """
Given a registry packages map (as produced by `tooling/registry/index@0.1.0`), this
component selects the best matching component entry for a requested id and
version constraint.

It understands a subset of Semantic Versioning:

- exact versions (`1.2.3`)
- caret ranges (`^1.2.0`)
- tilde ranges (`~1.4.0`)
- wildcard suffixes (`1.2.x`, `1.x`)
- `*` / `latest`"""
