schemaVersion = "1.0"
id = "lcod://tooling/resolver@0.1.0"
name = "resolver"
namespace = "tooling"
version = "0.1.0"
kind = "workflow"
summary = "Composite resolver that produces lcp.lock from lcp.toml using filesystem/network axioms."

[tool]
name = "resolve"
description = "Resolve dependencies and produce an lcp.lock"
inputSchema = "schema/resolve.in.json"
outputSchema = "schema/resolve.out.json"

[deps]
requires = [
  "lcod://axiom/fs/write-file@1",
  "lcod://flow/foreach@1",
  "lcod://contract/tooling/resolve-dependency@1",
  "lcod://impl/set@1",
  "lcod://resolver/internal/load-descriptor@1",
  "lcod://resolver/internal/load-config@1",
  "lcod://resolver/internal/lock-path@1",
  "lcod://resolver/internal/build-lock@1"
]

[docs]
readme = "README.md"
