name: Close Issues From Roadmap

on:
  push:
    paths:
      - 'ROADMAP.md'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const text = fs.readFileSync('ROADMAP.md','utf8');
            const done = [];
            const re = /^- \[x\]\s*(M0-\d+)\b.*$/gmi;
            let m; while ((m = re.exec(text)) !== null) { done.push(m[1]); }
            if (!done.length) { core.info('No done items found.'); return; }
            const issues = await github.paginate(github.rest.issues.listForRepo, { owner: context.repo.owner, repo: context.repo.repo, state: 'open' });
            for (const code of done) {
              const match = issues.find(i => i.title.startsWith(code + ' '));
              if (match) {
                await github.rest.issues.update({ owner: context.repo.owner, repo: context.repo.repo, issue_number: match.number, state: 'closed' });
                core.info(`Closed issue #${match.number} for ${code}`);
              }
            }
