schemaVersion = "2.0"
id = "lcod://contract/tooling/array/flatten@1.0.0"
version = "1.0.0"
kind = "contract"
summary = "Flatten an array one level deep, discarding nullish entries."

[tool]
name = "tooling_array_flatten"
description = "Flattens nested arrays by one level."
inputSchema = "schema/flatten.in.json"
outputSchema = "schema/flatten.out.json"

[documentation]
body = """
Returns a new array composed of the non-null values from the input sequence.
Nested arrays are expanded by one level, while `null` and `undefined` entries
are removed."""
