schemaVersion = "1.0"
id = "lcod://contract/core/json/decode@1.0.0"
name = "decode"
namespace = "contract/core/json"
version = "1.0.0"
kind = "contract"
summary = "Parse JSON text into structured data."

[tool]
name = "core_json_decode"
description = "Parse an in-memory JSON string (shorthand for core/parse/json)."
inputSchema = "schema/decode.in.json"
outputSchema = "schema/decode.out.json"

[docs]
readme = "README.md"
